# google cloud authentication,
# stores login data in ~/.config/gcloud which is mounted to the container
#
# gcloud auth application-default login
#

version: '3'
services:
  gallery:
    build: gallery/.
    ports:
     - "9000:9000"
    volumes:
     - "~/.config/gcloud:/root/.config/gcloud"
  upload:
    build: upload/.
    ports:
     - "8080:8080"
    links:
     - "generator:generator"
    environment:
     - thumbnail-service.hostname=generator
     - thumbnail-service.port=8888
    volumes:
     - "~/.config/gcloud:/root/.config/gcloud"
  generator:
    build: generator/.
    volumes:
     - "~/.config/gcloud:/root/.config/gcloud"