apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: thumby-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thumby-gateway-vs
spec:
  hosts:
  - "*"
  gateways:
  - thumby-gateway
  http:
  # prefix gallery route to gallery service
  - match:
    - uri:
        prefix: /gallery
    route:
    - destination:
        host: gallery-service
        port:
          number: 9000
  - match:
    - uri:
        prefix: "/health"
    route:
    - destination:
        host: upload-service
        port:
          number: 8080
    fault:
      delay:
        percent: 100
        fixedDelay: 5s
  - match:
    - uri:
        prefix: "/generator-status"
    route:
    - destination:
        host: upload-service
        port:
          number: 8080
    # note: retries only react on 5xx status code
    #       (retrying on 4xx make not much sense, have to handled on application side)
    retries: # retry request in case of failure on /generator-status request
      attempts: 2
      perTryTimeout: 1s
  # default route to upload service
  - route:
    - destination:
        host: upload-service
        port:
          number: 8080
    # global retry for upload-service
    #retries: # retry request in case of failure
    #  attempts: 2
    #  perTryTimeout: 1s
