apiVersion: v1
kind: Service
metadata:
  name: thumby-gallery-service
  namespace: default
spec:
  ports:
  - port: 9000
    protocol: TCP
    name: http
  selector:
    app: thumby-gallery
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumby-gallery
spec:
  selector:
    matchLabels:
      app: thumby-gallery
  replicas: 1
  template:
    metadata:
      labels:
        app: thumby-gallery
    spec:
      containers:
      - name: thumby-gallery-app
        image: gcr.io/carbide-parser-205909/gallery-service:1
        ports:
        - containerPort: 9000
        env:
        - name: BUCKET_NAME
          value: thumbnail-service